# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: spuisais <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/14 12:08:45 by spuisais          #+#    #+#              #
#    Updated: 2018/11/12 13:01:13 by spuisais         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = gcc

CFLAGS = -Wall -Wextra -Werror

NAME = ft_display_file

all    :
		$(CC) -o $(NAME) $(NAME).c

clean :
	    rm -rf *.o

fclean : clean
	    rm -rf $(NAME)

re : fclean all
